var assets = {
	"holiday_movies": [
		"excessive garland",
		"bad hair on the guy",
		"fake snow",
		"person of color with trivial role",
		"recognize from a different hallmark christmas movie",
		"wizened old person",
		"love triangle ",
		"old boyfriend casts a shadow",
		"single dad ",
		"inclement weather ",
		"stock photo montage",
		"wedding/proposal",
		"working in family's store",
		"event planner",
		"frustrated creative type",
		"christmas decoration as a metaphor",
		"someone complains about the game",
		"fun screen transition",
		"cute kid with uncomfortable observation",
		"cute kid with wish",
		"cute kid foreshadowing",
		"strange christmas tradition",
		"drinking christmas drink",
		"overly decorated christmas tree",
		"flocked christmas tree",
		"out of place christmas carolers",
		"ice skating",
		"awkward dancing scene",
		"gratuitous charity work",
		"snobby in-laws",
		"multiple christmas trees in a scene",
		"young lady freshening up",
		"baking",
		"bad lip synching ",
		"blue balls",
		"writing a letter",
		"surprise snow",
		"falling in love in <>3 days",
		"rediscovers love of christmas",
		"reads 'twas the night before christmas ",
		"deceased parent",
		"workaholic parent",
		"pointless misunderdtanding used to further plot",
		"scrooge like character",
		"unnecesarily jealous person",
		"acoustic music interlude",
		"christmas presents under an outdoor tree",
		"thinly veiled religion references",
		"magic",
		"single mother",
		"snobby parents",
		"singing"
	]
};
